### PR TITLE
Add Titanic survivors prediction

### PR DESCRIPTION
**Pull request by Asutosh989**
I have added the Titanic Survivors prediction which gives the accuracy score of 0.79425 in Kaggle. The output which can be checked is in the "best_output" folder.

### CODE REVIEW

**Comment by vermashresth** [comment]
@Asutosh989 can you please add your solution in the already existing TitanicSurvivalPrediction folder?
It will keep the directory structure clean and more organized.

**Comment by Asutosh989** [comment]
Should I add only the solution csv file to the already existing TitanicSurvivalPrediction folder or my whole folder?

**Comment by vermashresth** [comment]
@Asutosh989  Add it as a sub folder

**Comment by Asutosh989** [comment]
I will add it as a subfolder and create a PR.

**Pull request merged**
